### ISSUE TITLE
Update application form to comply with DfE requirements in time for FAC23

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site-v3#160]
See today's communications on Discord in #applicant-journey.

**Comment by oliverjam** [comment]
Currently tracking this on the new WIP platform, which I think will be a better fit. Given the amount of work required to update the existing form I don't think it'll be any slower to do it from scratch on the new one

https://github.com/fac-team/fac-account/issues/9

**Comment by oliverjam** [comment]
Okay U-turn since there's not enough time to finish the new platform. I'll be updating the existing form today. This will probably involve removing/merging some of our existing questions to fit the DfE requirements.

I'll have some questions about this, which I'll post here so @yvonne-liu has a chance to look at them when she wakes up.

**Comment by oliverjam** [comment]
1. Can we drop "Are you free of work and study commitments for the duration of the programme?"
   - "The programme" now includes a part-time course where they _can_ have other commitments.
   - We'll already have "Do you plan to work during the pre-apprenticeship programme?" from the DfE
   - Maybe it should change to be explicitly about the full-time course?
